export const cups = [
        {
        id: 0,
        name:'Microwave Safe Ceramic Polka Dotted Cups - Sets of 6',
        image: '/images/microwavecups.jpg',
        label:'New',
        price:'350',
        description:'Presenting the highly styled Microwave Safe Ceramic Polka Dotted Cups, which is exclusively made by Ceramic material. It is tough and brittle in nature and come in different style with a set of 6',
        },
        {
        id: 1,
        name:'The Earth Store Ceramic Handcrafted Microwave Safe Cream Polka Dot Printed Tea Cup/Coffee Cup Set Ideal Best Gift for Friends, Family, Home, Office use, Kitchen Cup',
        image: '/images/Earthpolka.jpg',
        label:'New',
        price:'349',
        description:'Package Contents: 6 Pieces of Tea / Coffee cups. These tea cups are hand made & hand crafted from good grade ceramic material. Color: Cream Multicolor. These cups enhance your tea/chai/coffee drinking experience and bring a ceremonial ending to each cup of tea. \n These cups are perfect for special occasions, parties and your special tea time.\n Start your morning with your favorite cup of tea/coffee, If you are looking for the best and unique tea cups set for your Coffee, Evening tea, Bed tea, Black tea, Green tea then these cups are the best option for you.',
        },
        {
        id: 2,
        name:'Clay Craft - Mike Coffee Mugs Set, 6-pieces, 210ml, MW28',
        image: '/images/clay.jpg',
        label:'New',
        price:'420',
        description:'Made of high quality Ceramic material.Durable and Chip Resistant. The stylish design of the cups or mugs look visually appealing and is an excellent way to welcome your guests with Lead & Cadmium. Free Made In India Color: MULTICOLOUR, Material: Ceramic.Package Contents: 6 Coffee Mugs.',
        },
        {
        id: 3,
        name:'MARINER CREATION® Colorful Classic Tea Cup Sets of 6 Ceramic - Unique Great Designed with Comfortable Strong Handle Serve Hot Tea and Coffee with Joy and Happiness - Multicolor',
        image: '/images/joy.jpg',
        label:'New',
        price:'475',
        description:'High Quality Materials: Our teacup set of 6 is made of the high quality ceramic materials. It is food safe and add extra beautiful style, serve as a decor on your table.Multicolored for different moods - a colorful treat to your eyes while your loved ones are sipping the evening tea with you Exquisite decorative patterns: The design of the pattern is exquisite. It is a perfect combination of art and practicality. The shape is designed to be unique and chic. This set can be given as a house-warming, wedding or anniversary gift. Space Saving Design - Designed to stack, these stackable mug set makes the most of kitchen storage with a modern, saves cabinet space.',
        },
        {
        id: 4,
        name:'The Earth Store Ceramic Handcrafted Microwave Safe Blaze Tea Cup/Coffee Cup Set Ideal Best Gift for Friends, Family, Home, Office use, Kitchen Cup (Set of 6, 220 ML)',
        image: '/images/blaze.jpg',
        label:'New',
        price:'649',
        description:'Package Contents: 6 Pieces of Tea / Coffee cups (220 ML each). These cups are hand crafted from good grade ceramics. Color: Wooden Brown. These cups enhance your tea / chai / coffee drinking experience and bring a ceremonial ending to each cup of tea. These cups are perfect for special occasions, parties and your special tea time. Start your morning with your favorite cup of tea/coffee, If you are looking for the best and unique tea cups set for your Coffee, Evening tea, Bed tea, Black tea, Green tea then these cups are the best option for you.',
        },
        {
        id: 5,
        name:'The Earth Store Handcrafted Ceramic Pastel Conical Multicolor Microwave Safe Chai/Tea Cups Serving Tea Mugs Set Best Gift for Friends, Anniversary, Birthday (Set of 6, 170 ML)',
        image: '/images/pastel.jpg',
        label:'New',
        price:'449',
        description:'✔ Package Contents:-Set of 6 Tea Cups ✔ Color:-Multicolor ✔ Capacity: 170 ML ✔ No Bone Ash. These cups are hand made & hand crafted from good grade ceramics.These cups are made without any chemical process, reusable and washable also it is microwave safe and 100% Handmade out of clay, fired at high temperatures by the hard working potters of Uttar Pradesh, India These cups enhance your tea/chai/coffee drinking experience and bring a ceremonial ending to each cup of tea. These cups are perfect for special occasions, parties and your special tea time. Start your morning with your favorite cup of tea/coffee, If you are looking for the best and unique tea cups set for your Coffee, Evening tea, Bed tea, Black tea, Green tea then these cups are the best option for you. Ideal Gift For Special Occasions: Perfect to give someone something meaningful that they will cherish forever and smile when they look at it and remember! Best Gift For Office, Father, Brother, Sister, Kids, Children For Birthday Return Gift, Birthday Gift, Birthday Party Gift, Family, Friends, Mother, Diwali Gift Items, Valentine Day Gift, Gifts For Girlfriend, Boyfriend Love, Husband and For Loved Ones.',
        },
        {
        id: 6,
        name:'POTZO Black Coffee Mugs, Combo of 6 Mugs, 250 ML, Handmade Microwave Safe Ceramic Mugs (6, Pure Black)',
        image: '/images/combo.jpg',
        label:'New',
        price:'649',
        description:'250 ML capacity. Microwave Safe | Dishwasher Safe | Freezer Safe | Food Grade . Handmade Product . Uses for tea, Coffee, Milk, etc . The mug is drinking, and eating safe',
        },
        {
        id: 7,
        name:'POTZO Modern Golden Eagle Coffee Mugs, 250 ML, Set of 6, Microwave Safe, Dishwasher Safe Stoneware Ceramic',
        image: '/images/Eagle.jpg',
        label:'New',
        price:'749',
        description:'250 ML capacity. Microwave Safe | Dishwasher Safe | Freezer Safe | Food Grade. Handmade, crafted with hand thrown clay and earthen material. Highly Durable Gloss/Matt shine and its color will last for lifetime. Fired at very high temperatures to bring out the finest quality.',
        },
        {
        id: 8,
        name:'Knitroot Printed Ceramic Coffee Mug 250 Ml White Color Coffee Then Coding',
        image: '/images/knitroot.jpg',
        label:'New',
        price:'249',
        description:'Guaranteed to last microwave and dishwasher safe. our mugs are printed on both sides. Permanent prints on the mug ensure they look delight on your desk at home or office.. Makes an wonderful gift to your loved ones. White color 250ml capacity. Makes an wonderful gift to your loved ones',
        },
        {
        id: 9,
        name:'Cupshup Ceramic Floral Mugs (Good Luck to You) (300 ml ) ( Set of 2 )',
        image: '/images/Floral.jpg',
        label:'New',
        price:'599',
        description:'FEATURES - Dishwasher Safe | Microwave Safe | Freezer Safe | Non Toxic | BPA Free | Environment Friendly | Reusable and Odorless, Material: - Ceramic | Quality Digital Printing | Premium quality gloss finished, Package Contents: 1-Piece Tea/Coffee Mug (350ml). Easy to Clean and Maintain: "CupShup" Mug is easy to clean. It can be easily clean with mild detergent or dish wash liquid on the inside. Do not use very rough cleaning sponges or bleaches, as they may damage by leaving scratch marks. Exclusive Eyecatching & Stylish Textured designer Coffee Mug developed by "CupShup" brand for a wide variety of customer tastes. Our Coffee Cups Make a Great Gift For Anybody, Men Women Mom Dad Grandma Grandpa Brother Sister Son Daughter Husband Wife Boyfriend Girlfriend Best Friend In Laws , Co-workers Employees Boss Friend Second Cousin Aunts And Uncles Him and Her Or Just Anybody Who Enjoys A Nice Cup Of Coffee In The Morning. The colors of the print may slightly vary from the image due to lighting effect. However, there wont be any compromise in product and print quality.',
        }
    ];

