export const pots =
    [
        {
        id: 0,
        name:'Plantmojo, Combo of Golden Money, Golden Snake & Jade Plant, in White Ceramic Pot with Saucer',
        image: '/images/goldenpot.jpg',
        label:'New',
        price:'999',
        description:'Golden money plant is a good indoor plant as it can prosper even in low light. Removes indoor pollutants and is an air purifier. Can be placed in living room, balcony, bedroom or in hanging baskets. It can prosper in any kind of soil, whether Clay, drought condition soil or soil full of small stones. Can survive in low light to direct sunlight, thus making it a very easy to care plant. Golden snake is a NASA recommended Air purifier plant. Unlike most other plants which release oxygen throughout the day, it releases stored oxygen as the stomata open in the night. Jade plants are succulent house-plants, which means that they dont need much water to survive as succulents are originally rocky desert plants. This makes them fairly resilient and easy to grow indoors and are amongst the most popular indoor plants. All 3 plants are low maintenance as money plant can grow under literally any condition, snake plants can prosper in shade, only Jade will need a little bit of sun during the week, else starts shedding leaves. Jade & Snake plants can survive in less water as well. Plants are provided in Matt white ceramic pot with saucer (3.4 inch height and 3.2 inch pot dia) which is ideal to place indoors and is aesthetically very pleasant',
        },
        {
        id: 1,
        name:'Ugaoo Sansevieria Golden Hahnii Snake Plant with Self Watering Pot',
        image: '/images/hahnii.jpg',
        label:'New',
        price:'445',
        description:'Air Purifier Plant. This plant is low on maintenance and is often seen in corridors and corners of the living room. Watering Schedule - once a week. Plant height - 6 to 12 inch; Natural Plant with 4 inches to 5 inches Diameter Pot. A little bit of color shade may vary as these are live plants',
        },
        {
        id: 2,
        name:'Ugaoo Indoor Plants With Pot For Home - Syngonium Pink & Money Plant Variegated',
        image: '/images/pink.jpg',
        label:'New',
        price:'649',
        description:'Combo Pack Contents: Natural Live Plant in Self Watering Pot, Qty: 2 (Plant with Pot). Unique leaf patterns make these plants perfect for living room & home decor. Light pink coloured leaves that can brighten your room or desk. Provide the rooms with a colourful leaf display. Plant height - 6 to 12 inch. Watering Schedule - Twice a week.',
        },
        {
        id: 3,
        name:'UGAOO Football Ceramic Pot (White, 5.1 Inch Diameter)',
        image: '/images/football.jpg',
        label:'New',
        price:'425',
        description:'Dimension: 13cm x 13cm x 11cm and 5.1 Inches Top Diameter. Enhance Your Home Decor With this beautiful Pot. Suitable For All Type of Plants. Perfect For Dining Table, Balcony, Living room. A Hole At The Bottom To Drain Out Excess Water.',
        },
        {
        id: 4,
        name:'Ugaoo Honeycomb Ceramic Pot (White)',
        image: '/images/honeycomb.jpg',
        label:'New',
        price:'249',
        description:'Item Dimension: 10 cm x 10 cm x 10 cm. Enhance your home decor with this beautiful pot. Suitable for all type of plants. Perfect for dining table or office desks. A hole at the bottom to drain out excess water',
        },
        {
        id: 5,
        name:'Ugaoo Good Luck Indoor Plants For Home With Pot - Jade Plant & Money Plant Variegated',
        image: '/images/variegated.jpg',
        label:'New',
        price:'649',
        description:'Material: Natural Live Plant in Self Watering Pot, Qty: 2 (Plant with Pot). Money Plant : This fleshy climbing vine in your indoor or outdoor space to create a spell-binding decor.. Jade Mini : It has thick, shiny, smooth, leaves that grow in opposing pairs along the branches. Symbolizes Great Friendship, Fortune & Prosperity. Watering Schedule - Twice a week.',
        },
        {
        id: 6,
        name:'ecofynd [2 Pack] ecofyndÂ® 4.3 inches Round Metal Planter for Home Decor, Set of 2 (White)',
        image: '/images/round.jpg',
        label:'New',
        price:'413',
        description:'【Premium Eco-friendly Metal Planters】 NOTE: Color of the pot may slightly varies in the shades of white. Carefully choosing super lightweight, sturdy metal, making such classy, durable, thick planters, no odor, hard to broken, makes the plant rotation process much easier and works great around kids or lively animals, great for decorate windowsill, desktop, shelf, bedroom, living room, kitchen, garden, office, etc. 【Perfect for Macrame Planters】 Set of 2 mini plant pots. 4.3” or 11 cm in Opening Diameter, 4.7” or 12cm in Depth, No DRAINAGE HOLES. This size is perfect to put in your hanging macramé, suitable for planting most small and medium-sized home/office plants like orchid, snake plant, mint, parlor palm, herbs, devil’s ivy, cactus, aloe, to brighten up your living place. 【PRACTICAL】 The golden flower pots reflect beautiful colors in the sun and light. They are a great choice for your living room, bedroom, office desk top and coffee table. Its a perfect match for all kinds of colorful plant flowers, so decorate your indoor environment with green plants and purify the air. Buy a beautiful decorative planter for yourself or give it as a housewarming, birthday, or Festival gift for friends and family. 【Minimalist Styled Plant Pots】 The Flower Plant Pots are designed with matte finishing exterior in soft, round shapes, bringing out a modern minimalistic styled like visual representation, fits for any home/office décor. And smooth glossy inner finish for easy cleaning. Great for replanting, and for flower plant lovers. 【A GREAT GIFT】 – Know someone with green fingers? Treat that special person to a gift that adds heaps of charm',
        },
        {
        id: 7,
        name:'Ugaoo Air Purifier Indoor Plants for Home with Pots- Areca Palm & ZZ Plant',
        image: '/images/areca.jpg',
        label:'New',
        price:'949',
        description:'Material: Natural Live Plant in Premium Plastic Pot, Qty: 2 (Plant with Pot). These are one of the most attractive, durable and tolerant houseplants. It handles low light and needs less water. Removes Formaldehyde, Benzene & Carbon Monoxide. Best Indoor Air Purifier Plants for home and office desk.',
        },
        {
        id: 8,
        name:'Ugaoo Watermelon Ceramic Planter (Multicolour)',
        image: '/images/watermelon.jpg',
        label:'New',
        price:'295',
        description:'Dimension: 15 cm x 7.5 cm x 9.5 cm and 5.9 Inches Width. Enhance Your Home Decor With this beautiful Pot. Suitable For All Type of Plants. Perfect For Dining Table or Office Desks. A Hole At The Bottom To Drain Out Excess Water.',
        }
    ];
