export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CHANGE_CART_QTY = "CHANGE_CART_QTY";
export const CART_RESET = "CART_RESET";

export const GET_CUPS_REQUEST = "GET_CUPS_REQUEST";
export const GET_CUPS_SUCCESS = "GET_CUPS_SUCCESS";
export const GET_CUPS_FAIL = "GET_CUPS_FAIL";

export const GET_CUPS_DETAIL_REQUEST = "GET_CUPS_DETAIL_REQUEST";
export const GET_CUPS_DETAIL_SUCCESS = "GET_CUPS_DETAIL_SUCCESS";
export const GET_CUPS_DETAIL_FAIL = "GET_CUPS_DETAIL_FAIL";
export const GET_CUPS_DETAIL_RESET = "GET_CUPS_DETAIL_RESET";

export const GET_PLATES_REQUEST = "GET_PLATES_REQUEST";
export const GET_PLATES_SUCCESS = "GET_PLATES_SUCCESS";
export const GET_PLATES_FAIL = "GET_PLATES_FAIL";

export const GET_PLATES_DETAIL_REQUEST = "GET_PLATES_DETAIL_REQUEST";
export const GET_PLATES_DETAIL_SUCCESS = "GET_PLATES_DETAIL_SUCCESS";
export const GET_PLATES_DETAIL_FAIL = "GET_PLATES_DETAIL_FAIL";
export const GET_PLATES_DETAIL_RESET = "GET_PLATES_DETAIL_RESET";

export const GET_POTS_REQUEST = "GET_POTS_REQUEST";
export const GET_POTS_SUCCESS = "GET_POTS_SUCCESS";
export const GET_POTS_FAIL = "GET_POTS_FAIL";

export const GET_POTS_DETAIL_REQUEST = "GET_POTS_DETAIL_REQUEST";
export const GET_POTS_DETAIL_SUCCESS = "GET_POTS_DETAIL_SUCCESS";
export const GET_POTS_DETAIL_FAIL = "GET_POTS_DETAIL_FAIL";
export const GET_POTS_DETAIL_RESET = "GET_POTS_DETAIL_RESET";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";
